/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChefsRouteImport } from './routes/chefs'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoodIdRouteImport } from './routes/food.$id'
import { Route as ChefIdRouteImport } from './routes/chef.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsRoute = ChefsRouteImport.update({
  id: '/chefs',
  path: '/chefs',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIdRoute = FoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefIdRoute = ChefIdRouteImport.update({
  id: '/chef/$id',
  path: '/chef/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chefs': typeof ChefsRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/restaurants': typeof RestaurantsRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/tracking': typeof TrackingRoute
  '/category/$slug': typeof CategorySlugRoute
  '/chef/$id': typeof ChefIdRoute
  '/food/$id': typeof FoodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chefs': typeof ChefsRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/restaurants': typeof RestaurantsRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/tracking': typeof TrackingRoute
  '/category/$slug': typeof CategorySlugRoute
  '/chef/$id': typeof ChefIdRoute
  '/food/$id': typeof FoodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chefs': typeof ChefsRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/restaurants': typeof RestaurantsRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/splash': typeof SplashRoute
  '/tracking': typeof TrackingRoute
  '/category/$slug': typeof CategorySlugRoute
  '/chef/$id': typeof ChefIdRoute
  '/food/$id': typeof FoodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/chefs'
    | '/login'
    | '/otp'
    | '/restaurants'
    | '/search'
    | '/signup'
    | '/splash'
    | '/tracking'
    | '/category/$slug'
    | '/chef/$id'
    | '/food/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/chefs'
    | '/login'
    | '/otp'
    | '/restaurants'
    | '/search'
    | '/signup'
    | '/splash'
    | '/tracking'
    | '/category/$slug'
    | '/chef/$id'
    | '/food/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/chefs'
    | '/login'
    | '/otp'
    | '/restaurants'
    | '/search'
    | '/signup'
    | '/splash'
    | '/tracking'
    | '/category/$slug'
    | '/chef/$id'
    | '/food/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ChefsRoute: typeof ChefsRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SplashRoute: typeof SplashRoute
  TrackingRoute: typeof TrackingRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ChefIdRoute: typeof ChefIdRoute
  FoodIdRoute: typeof FoodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs': {
      id: '/chefs'
      path: '/chefs'
      fullPath: '/chefs'
      preLoaderRoute: typeof ChefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$id': {
      id: '/food/$id'
      path: '/food/$id'
      fullPath: '/food/$id'
      preLoaderRoute: typeof FoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/$id': {
      id: '/chef/$id'
      path: '/chef/$id'
      fullPath: '/chef/$id'
      preLoaderRoute: typeof ChefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ChefsRoute: ChefsRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  RestaurantsRoute: RestaurantsRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SplashRoute: SplashRoute,
  TrackingRoute: TrackingRoute,
  CategorySlugRoute: CategorySlugRoute,
  ChefIdRoute: ChefIdRoute,
  FoodIdRoute: FoodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
